title: Minhs Blog
email: mh98ngo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Das ist mein Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minhs-blog.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
author: Minh Ngo
profile: /assets/images/profiles/minh.png
twitter_username: mh_no_8
github_username: MinhNgo-98
facebook_username: mhno.8
instagram_username: mh_no.8
linkedin_username: minhngo-3598

# Build settings
theme: minima
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: compressed

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/img"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
