title: Minhs Blog
email: mh98ngo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Das ist mein Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Minh Ngo
profile: /assets/images/profiles/minh.png
twitter_username: mh_no_8
github_username: MinhNgo-98
facebook_username: mhno.8
instagram_username: mh_no.8
linkedin_username: minhngo-3598

# Build settings
theme: minima
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: compressed